# AndroidX??
android.useAndroidX=true
android.enableJetifier=true

# Kotlin????
kotlin.code.style=official

# Gradle????
org.gradle.jvmargs=-Xmx4608m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true

# ????
android.injected.testOnly=false

# AGP 8.0+???
android.nonTransitiveRClass=true
#android.defaults.buildfeatures.buildconfig=true
