pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "MaxRTB"

include ':core'
include ':zx'
include ':zxdm'
// include ':baidu'
// include ':csj'
// include ':demo'
// include ':gdt'
// include ':ks'
// include ':mg'
// include ':zhixuan'
// include ':zxdemo'