apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.maxrtb.zhixuan'
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.android.minSdkVersion
        targetSdkVersion rootProject.ext.android.targetSdkVersion
        versionCode rootProject.ext.android.versionCode
        versionName rootProject.ext.android.versionName
        
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding false
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    lint {
        disable 'MissingTranslation'
        disable 'ExtraTranslation'
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    // Kotlin
    implementation rootProject.ext.libraries.kotlinStdlib
    implementation rootProject.ext.libraries.kotlinCoroutinesCore
    implementation rootProject.ext.libraries.kotlinCoroutinesAndroid

    // AndroidX
    implementation rootProject.ext.libraries.androidxCore
    implementation rootProject.ext.libraries.androidxAppcompat
    implementation rootProject.ext.libraries.androidxConstraint

    // 网络框架（新增）
    implementation rootProject.ext.libraries.okhttp3
    implementation rootProject.ext.libraries.okhttpLogging
    implementation rootProject.ext.libraries.retrofit2
    implementation rootProject.ext.libraries.retrofitGson
    implementation rootProject.ext.libraries.retrofitScalars

    // 序列化
    implementation rootProject.ext.libraries.gson

    // 图片加载
    implementation rootProject.ext.libraries.glide
    kapt rootProject.ext.libraries.glideCompiler

    // 测试
    testImplementation rootProject.ext.libraries.junit
    androidTestImplementation rootProject.ext.libraries.testExt
    androidTestImplementation rootProject.ext.libraries.espresso
}
