plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    namespace 'com.maxrtb.zxdm'
    compileSdk rootProject.ext.android.compileSdkVersion

    defaultConfig {
        applicationId "com.maxrtb.zxdm"
        minSdk rootProject.ext.android.minSdkVersion
        targetSdk rootProject.ext.android.targetSdkVersion
        versionCode rootProject.ext.android.versionCode
        versionName rootProject.ext.android.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
        freeCompilerArgs += [
            '-opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi'
        ]
    }

    buildFeatures {
        viewBinding true
    }

    lint {
        disable 'MissingTranslation'
        disable 'ExtraTranslation'
    }
}

dependencies {
    implementation project(':zx')
    implementation project(':core')

    implementation rootProject.ext.libraries.kotlinStdlib
    implementation rootProject.ext.libraries.kotlinCoroutinesCore
    implementation rootProject.ext.libraries.kotlinCoroutinesAndroid
    implementation rootProject.ext.libraries.androidxCore
    implementation rootProject.ext.libraries.androidxAppcompat
    implementation rootProject.ext.libraries.androidxConstraint
    implementation rootProject.ext.libraries.material
    implementation rootProject.ext.libraries.lifecycleRuntime
    implementation rootProject.ext.libraries.lifecycleViewModel
    implementation rootProject.ext.libraries.okhttp3
    implementation rootProject.ext.libraries.okhttpLogging
    implementation rootProject.ext.libraries.gson
    implementation rootProject.ext.libraries.glide
    kapt rootProject.ext.libraries.glideCompiler

    testImplementation rootProject.ext.libraries.junit
    androidTestImplementation rootProject.ext.libraries.testExt
    androidTestImplementation rootProject.ext.libraries.espresso
}
